# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-23 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meandhim', '0002_auto_20180123_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quest',
            field=models.CharField(default='firas', max_length=200),
            preserve_default=False,
        ),
    ]
